input_file = open(r'C:\\Networks\work\\files\\lyrics.txt','r')
#lyrics = input_file.read()
#print(lyrics)
lyrics = input_file.readline()
print(lyrics)
lyrics = input_file.readline()
print(lyrics)
lyrics = input_file.readline(10)
print(lyrics)
